# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

split_df_cpp <- function(df) {
    .Call('Newsmap_split_df_cpp', PACKAGE = 'Newsmap', df)
}

